### ISSUE TITLE
SDK with java 8

### ISSUE THREAD

**Issue by pingupingu9999** [fattureincloud/fattureincloud-java-sdk#58]
Hi, good morning! I installed the gradle dependency and tried to use it, but when i run my application it says me that i need a more recent version of java.
Am I missing something? Or is there any version that i can use for java 8? 
Thanks in advance!

**Comment by pingupingu9999** [comment]
Grazie mille della risposta celere! Parlo in italiano così almeno ci capiamo prima.
Adesso funziona e compila, tutto perfetto!
Solo che ho trovato un piccolo problema e non so se ho configurato male io la cosa, anche se in realtà ho fatto un copia e incolla, ma quando vado a fare UserApi getUserInfo(), mi da questo errore:
java.lang.IllegalArgumentException: The field `details` in the JSON string is not defined in the `GetUserInfoResponseEmailConfirmationState` properties. JSON: {"need_confirmation":false,"details":{"is_first_email":true,"email":"helpline@pointoffice.it","token_expired":true}}
Ho copiato esattamente il codice presente nell'esempio e mi da questo errore, puoi darmi una mano?
Grazie ancora del supporto, buona serata!

**Comment by pingupingu9999** [comment]
Buongiorno! Scusate ancora il disturbo, ma continuo a trovare piccoli errori e non capisco se sto sbagliando io qualcosa, oppure è effettivamente così. Tutte le chiamate che faccio con questi esempi che vedo qui sopra, mi vanno tutti in errore "NoSuchMethodError" al che ho visto che la chiamata "RequestBody.create(MediaType, String)" veniva utilizzata ma scambiando i parametri della funzione, quindi con la stringa al posto del MediaType e viceversa.
Ho importato il file come esterno, ho cambiato quella parte e non ho più quell'errore.
Adesso però, continuo a ricevere errore "Unhautorized", come se l'access Token non venisse minimamente considerato.
Ti lascio una foto dell'errore che ricevo!
Grazie mille, buona giornata!

![Unhautorized](https://user-images.githubusercontent.com/100719209/175906262-65ed56d5-f86a-441c-9489-dde167843cad.PNG)

**Comment by emajo** [comment]
Ciao, abbiamo rilasciato la versione 2.0.10 per sistemare un bug, ti direi di provare con quella, anche se sembra che i problemi che stai riscontrando siano dovuti a versioni di dipendenze in conflitto, abbiamo provato a creare un nuovo progetto gradle e funziona tutto come dovrebbe, se con la 2.0.10 riscontri ancora gli stessi problemi ti chiederei di controllare se hai delle versioni di dipendenze nel tuo progetto diverse da quelle del nostro build.gradle che possano creare dei conflitti.

Grazie,
Emanuele

**Comment by pingupingu9999** [comment]
Ciao, ancora grazie mille della risposta! Va benissimo, verifico e ti farò sapere come va. 
Nel frattempo chiudo il topic, grazie per la disponibilità.

Lorenzo

**Comment by mauriziopinotti** [comment]
Nel mio caso, caricando l'SDK in un progetto Maven / Spring Boot su Java 8, mi trovavo tra le dipendenze OkHttp 3.8.1 e ricevevo l'errore citato sopra (`NoSuchMethodError` su `RequestBody.create(MediaType, String)`).

Per risolvere ho forzato l'utilizzo di OkHttp 4.x in questo modo:

```xml
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.7.10</version>
        </dependency>
```
