### ISSUE TITLE
Issue with Missing Fields in Company Data API Deserialization

### ISSUE THREAD

**Issue by marionee** [fattureincloud/fattureincloud-java-sdk#79]
Dear Support Team,

I am writing to report an issue I've encountered with the API for retrieving company data. Specifically, the API response includes the fields "fic_license_expire" and "fic_plan", but these fields are not present in the deserialized Company class. This omission leads to a significant inefficiency in our workflow.

Currently, without these fields in the Company class, we are forced to make an additional REST API call to determine if a company's license has expired. This is not only time-consuming but also increases the load on our systems.

Including "fic_license_expire" and "fic_plan" in the Company class would allow us to access this critical information directly from the initial API call, significantly streamlining our process. This change would help us avoid unnecessary additional API calls and reduce the risk of discovering license expiration through error responses.

Could you please look into this issue and consider updating the Company class to include these fields? This adjustment would greatly enhance the API's functionality and efficiency for our use case.

Thank you for your attention to this matter. I look forward to your prompt response.

Best regards.

**Comment by emajo** [comment]
Hi @marionee, sorry for the late response, we just released a new version of all our SDKs containing the fields you requested.

Thanks for reporting this issue,
Emanuele.

**Comment by marionee** [comment]
Hi @emajo, thank you for the update.
