### ISSUE TITLE
Special tax regime

### ISSUE THREAD

**Issue by marionee** [fattureincloud/fattureincloud-java-sdk#91]
Dear Support Team,

Is there a way through the API to see if the account has a special tax regime?
From the documentation, I can’t find a way to determine if a company is in the flat-rate regime.

Best regards.

**Comment by valmoz** [comment]
Hello @marionee 
this is not an issue related to the Java SDK, I'm closing this.

Please, feel free to open a new discussion in our [Community](https://github.com/fattureincloud/api/discussions) with the same content, we'll be happy to answer you there.

Thanks
Mauro
